#ifndef _CE_EVENT_TYPE_H_
#define _CE_EVENT_TYPE_H_

#include <cstdint>

enum class EventType : uint32_t
{
	SET_ANIMATION_TIME = 0,
	REQUEST_ANIMATION_STATE,
	ANIMATION_STATE,
	TOGGLE_PAUSE,
	REQUEST_PAUSE_STATE,
	PAUSE_STATE,
	SET_RENDER_MODE,
	REQUEST_FPS_STATE,
	FPS_STATE,
	TOGGLE_BIND_POSE,
	AVAILABLE_ANIMATION,
	REQUEST_AVAILABLE_ANIMATION,
	SET_ANIMATION
};

#endif // _CE_EVENT_TYPE_H_
