#ifndef _CE_EVENT_TYPE_H_
#define _CE_EVENT_TYPE_H_

#include <cstdint>

enum class EventType : uint32_t
{
	SET_ANIMATION_TIME = 0,
	REQUEST_ANIMATION_STATE,
	ANIMATION_STATE,
	TOGGLE_PAUSE,
	REQUEST_PAUSE_STATE,
	PAUSE_STATE,
	TOGGLE_RENDER_MODE
};

#endif // _CE_EVENT_TYPE_H_
